# -*- coding: utf-8 -*-
"""P-111.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ektNFgrBUiOY49u0-0ZSiK1Pj8EAhT2
"""

from google.colab import files
file_to_load=files.upload()

import plotly.figure_factory as ff
import plotly.graph_objects as go
import pandas as pd
import statistics
import random
import csv
df=pd.read_csv('data 2.csv')
data=df['Math_score'].tolist()
fig=ff.create_distplot([data],['Maths_score'],show_hist=False)
fig.show()
mean=statistics.mean(data)
standard_deviation=statistics.stdev(data)
print("Mean of population",mean)
print("Standard deviation of population",standard_deviation)

def random_set_of_mean(counter):
  dataset=[]
  for i in range(0,counter):
    random_index=random.randint(0,len(data)-1)
    value=data[random_index]
    dataset.append(value)
  mean1=statistics.mean(dataset)
  return mean1

mean1_list=[]
for i in range(0,1000):
  set_of_means=random_set_of_mean(100)
  mean1_list.append(set_of_means)

standard_deviation2=statistics.stdev(mean1_list)
mean3=statistics.mean(mean1_list)
print('Mean of Sampling distribution',mean3)
print("Standard Deviation of Sampling Distribution",standard_deviation2)

fig=ff.create_distplot([mean1_list],['Student Marks'],show_hist=False)
fig.add_trace(go.Scatter(x=[mean,mean],y=[0,0.20],mode="lines",name='mean'))
fig.show()

first_std_deviation_start,first_std_deviation_end=mean-standard_deviation2,mean+standard_deviation2
second_std_deviation_start,second_std_deviation_end=mean-(2*standard_deviation2),mean+(2*standard_deviation2)
third_std_deviation_start,third_std_deviation_end=mean-(3*standard_deviation2),mean+(3*standard_deviation2)
print("std1",first_std_deviation_start,first_std_deviation_end)
print("std2",second_std_deviation_start,second_std_deviation_end)
print("std3",third_std_deviation_start,third_std_deviation_end)

fig=ff.create_distplot([mean1_list],['Student Marks'],show_hist=False)
fig.add_trace(go.Scatter(x=[mean,mean],y=[0,0.20],mode="lines",name='mean'))
fig.add_trace(go.Scatter(x=[first_std_deviation_start,first_std_deviation_start],y=[0,0.20],mode="lines",name='standarddeviation1 start'))
fig.add_trace(go.Scatter(x=[first_std_deviation_end,first_std_deviation_end],y=[0,0.20],mode="lines",name='standard1end'))
fig.add_trace(go.Scatter(x=[second_std_deviation_start,second_std_deviation_start],y=[0,0.20],mode="lines",name='standard2 start'))
fig.add_trace(go.Scatter(x=[second_std_deviation_end,second_std_deviation_end],y=[0,0.20],mode="lines",name='standard2 end'))
fig.add_trace(go.Scatter(x=[third_std_deviation_start,third_std_deviation_start],y=[0,0.20],mode="lines",name='standard3 start'))
fig.add_trace(go.Scatter(x=[third_std_deviation_end,third_std_deviation_end],y=[0,0.20],mode="lines",name='standard3 end'))
fig.show()